### ISSUE TITLE
Could you include the UserList and ContactList code in your usage example

### ISSUE THREAD

**Issue by UmbraLimi** [lc3t35/ra-data-meteor#1]
Hi Laurent,

They don't need to be complete but I wanted to see how/if the code you have in your usage is reactive to changes in the database. Particularly the pub/sub code.

**Comment by sabativi** [comment]
Hum, yes it would be good to have a working example to see exactly where we are.

But regarding pub/sub code, I do not see any publications in the code so there will be no reactivity as far as I understand

**Comment by lc3t35** [comment]
I published this work in progress in dev branch, so other can participate to the TODO list  : 
`write a Meteor testbed with tests with Users and Contacts collections`, this should include how reactivity can be achieved for the react-admin package, wrapping the ContactList with withTracker.
Can't one of you both start to enhance the repo with a very simple example rather than waiting to see a working example (and me doing all the work) ?

**Comment by UmbraLimi** [comment]
It appeared from your usage example that you had those lists somewhere but hadn't included them yet (as this is the start of the repo). My request was only to ask. Similarly, and I may have gotten the wrong idea from past conversations, I had somehow gotten the idea that you had a reactive solution already, but not yet complete in its coverage of the data provider features of react-admin.

I am delighted to help, and so I will see if I can glean what you are doing. This is my first intended contribution to an npm package.

**Comment by mikkelking** [comment]
This may be a little old now, I would be interested to help, or at least get this to run and have a look at it. Clearly there was a meteor project you were interfacing with, and it would help to get that code to help get started :)

**Comment by lc3t35** [comment]
@mikkelking you can find additional work on this topic here : https://github.com/belthane/todo-list-ra-admin (dev branch)
I think it is much easier to build your own admin (with datatable) rather than relying on react-admin ...

**Comment by mikkelking** [comment]
Ok thanks, that's great - but you reckon trying to get react-admin to play nice with Meteor is too much trouble? I have my own  way, but I'm always interested in how other people tackle problems.

**Comment by lc3t35** [comment]
@mikkelking feel free to submit a PR fo fix or enhance the 2 repos ;)

**Comment by lc3t35** [comment]
examples are here : https://github.com/belthane/todo-list-ra-admin/tree/main/imports/ui/lists
